version: '3.9'

volumes:
  db-data:
    driver: local

services:
  postgresDB:
    image: postgres:13.3
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped